# Generated by Django 3.0.5 on 2020-04-28 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanager', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Areas',
        ),
    ]
